spring.application.name=TraceAndTrust

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/logistics-realm/protocol/openid-connect/certs

spring.security.oauth2.resourceserver.jwt.principal-claim-name=preferred_username

server.error.include-message=always