spring.application.name=TraceAndTrust
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
# JWT Configuration
jwt.secret=6a3iH1Jm+0WK+bDF/YwWZUNWcG26PNP1Z8ggldlZCGA=
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000


logging.logstash.destination=localhost:5000
