spring.application.name=TraceAndTrust
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
# JWT Configuration
jwt.secret=${JWT_SECRET:6a3iH1Jm+0WK+bDF/YwWZUNWcG26PNP1Z8ggldlZCGA=}
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000

logging.logstash.destination=${LOGINSTASH:localhost}:${LOGINSTASHPORT:5000}

# AWS S3 Configuration
spring.cloud.aws.credentials.access-key=${AWS_ACCES}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET}
spring.cloud.aws.region.static=${AWS_REGION:eu-north-1}
spring.cloud.aws.s3.bucket=${AWS_BUCKET_NAME:trace-and-trust-images-dilali}

# Multipart Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:logistics_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update